# Generated by Django 5.2.5 on 2026-01-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Ruby', 'Ruby'), ('Sapphire', 'Sapphire'), ('Emerald', 'Emerald'), ('Diamond', 'Diamond'), ('Amethyst', 'Amethyst'), ('Other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=100)),
                ('carat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('treatment', models.CharField(blank=True, help_text='e.g. Heat, None', max_length=100)),
                ('certification', models.CharField(blank=True, help_text='e.g. GIA, GRS', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='gemstones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
